spring.datasource.url=jdbc:postgresql://localhost:5432/leboncoin
spring.datasource.username=postgres
spring.datasource.password=example
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090

------------------------- AWS Credentials -------------------------

aws.region=eu-west-3
aws.s3.bucket=leboncoinp

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


security:
  jwt:
    secret: "sIvx3AMVwl2K8bWYGey4JqKDGH+8tkRhfrP8nEhbQq0CN43Sm5K0CaB3tknVBqWszHWi9ykY8Ku8dlIcKkFzpQ=="
    issuer: "leboncoinp"
    access-token-minutes: 60